// Datos iniciales de residentes ELEAM San Francisco - Gorbea.
// Se cargan una sola vez, la primera vez que se abre la app (si no hay
// datos guardados todavía). Después de eso, todo se administra y
// persiste desde la propia aplicación (editar, agregar, eliminar).
export const SEED_RESIDENTS = [
  { nombre: "Adriana Sepulveda Vidal", edad: "92", observaciones: "HTA, DLP, Alzheimer, Hipoacusia, Resistente a la Insulina" },
  { nombre: "Adriana del Carmen Alarcon Silva", edad: "86", observaciones: "Demencia por Alzheimer" },
  { nombre: "Alicia Imio Navarrete", edad: "74", observaciones: "DM2 IR, Demencia por Alzheimer, DLP, Epilepsia" },
  { nombre: "Ana Alicia Biava Bustos", edad: "85", observaciones: "Demencia Mixta Vascular y Alzheimer, HTA, ACV 2019, Enf. del nodo Sinusal, Arritmia Completa por fibrilación auricular en DACO, Glaucoma, Vicio Refracción." },
  { nombre: "Arnoldo Fuentes Barriga", edad: "88", observaciones: "HTA, DM2, DLP, Cardiopatía Coronaria, Parkinson" },
  { nombre: "Carmen Oldeni Zavala Ojeda", edad: "67", observaciones: "HTA, DM2 NIR, DLP, Artritis Reumatoide, Artrosis, Cardiopatía (En Estudio), Demencia (En Estudio)" },
  { nombre: "Doris Curiqueo Chihuailaf", edad: "61", observaciones: "Retraso Mental, Epilepsia" },
  { nombre: "Eduardo Jenaro Sanhueza Sepulveda", edad: "69", observaciones: "Demencia Mixta" },
  { nombre: "Eliana Muñoz Riffo", edad: "82", observaciones: "Demencia Alzheimer (E.A), DLP" },
  { nombre: "Eliana de las Mercedes Valenzuela Garces", edad: "87", observaciones: "DM NIR, HTA Controlada, DLP, Alzheimer" },
  { nombre: "Ema Ester Zapata Saldias", edad: "81", observaciones: "HTA, ICC, ERC 3, DM2, Arritmia Cardiaca por Fibrilación Auricular, Hipotiroidismo" },
  { nombre: "Ema Lizama Obreque", edad: "81", observaciones: "Demencia, Dolor ABD Crónico" },
  { nombre: "Ercira del Carmen Maldonado Cares", edad: "93", observaciones: "HTA, Artrosis, LCFA, EPOC, Fx de Húmero Derecho Operada en 2024" },
  { nombre: "Erna del Carmen Navarrete Aliaga", edad: "86", observaciones: "HTA, DM, DLP" },
  { nombre: "Erna del Carmen Rubilar Castro", edad: "84", observaciones: "Megacolon, Hipotiroidismo, Depresión, Marcapaso, DLP, IC Congestiva" },
  { nombre: "Esterlina Arratia Leal", edad: "98", observaciones: "Artrosis de rodilla, Fractura de cadera derecha, HTA compensada" },
  { nombre: "Fermin Alberto Aravena Guzman", edad: "81", observaciones: "HTA, DM2, DLP, Cardiopatía, ERC Etapa 3, AIM hace 10a" },
  { nombre: "Florindo de la Cruz Castillo Hidalgo", edad: "93", observaciones: "Hiperplasia Prostática" },
  { nombre: "Hilda Floridema Aburto Aburto", edad: "79", observaciones: "HTA, DLP, DM, Parkinson, Depresión" },
  { nombre: "Iris Yolanda Nahuelhual Barraza", edad: "97", observaciones: "Fx de Cadera Izquierda" },
  { nombre: "Isabel Elizabeth Sanhueza Tapia", edad: "67", observaciones: "Hipotiroidismo, Epilepsia, HTA, Depresión, Hipoacusia, Esquizofrenia, Cirugia colecistectomizado (Vesicula)" },
  { nombre: "Ismenia Hernandez Moreno", edad: "99", observaciones: "HTA, DM, Artritis, Fibrosis Pulmonar, Colon Irritable" },
  { nombre: "Jacinta Huichaqueo Antileo", edad: "86", observaciones: "Alzheimer, DLP, FX Cadera Derecha, HTA Controlada, Anemia en tratamiento" },
  { nombre: "Jeannette del Carmen Muñoz Quiñones", edad: "78", observaciones: "HTA, Artrosis de Rodilla, Demencia, DLP, Aneurisma Aórtico Abdominal" },
  { nombre: "Jerman de la Cruz Villa Duran", edad: "90", observaciones: "DLP" },
  { nombre: "Joel Cardenas Nuñez", edad: "86", observaciones: "Múltiples ACV, HTA, Artrosis, OH Crónico, DLP, Hipotiroidismo, Epilepsia" },
  { nombre: "Jose Abelardo Mondaca Zambrano", edad: "68", observaciones: "HTA, DLP, ACV, Alzheimer" },
  { nombre: "Jose Alejandro Ortega Troncoso", edad: "72", observaciones: "CA Prostata, Artrosis, AR, Cataratas, Colostomia Post Fournier" },
  { nombre: "Jose Baltazar Vines Alveal", edad: "87", observaciones: "HTA, IAM, Parkinson, Ca Prostata, DLP, Hipoacusia, Daño Hepatico, DM2, Artrosis de Rodilla y Cadera, AVE Secuelado, ASMA, EPOC, IRC, Usuario con Marcapaso" },
  { nombre: "Jose Miguel Cuevas Navarrete", edad: "75", observaciones: "Defecto de coagulacion, HTA, EPOC, DLP, LCC" },
  { nombre: "Jose Orosman Palma Aguilera", edad: "80", observaciones: "HTA, Poliartrosis, Carcinoma Espino Celular Operado, Insuficiencia Cardiaca" },
  { nombre: "Juana Matilde Higuera Rosales", edad: "92", observaciones: "DM2, Hipertensión Esencial, DLP, Depresión, Anemia, Insuficiencia Cardiaca" },
  { nombre: "Julia Manuela Valenzuela Medina", edad: "88", observaciones: "DLP, EPOC" },
  { nombre: "Lucas Marcelino Reyes Reyes", edad: "73", observaciones: "HTA, DLP" },
  { nombre: "Luis Omar Perez Ulloa", edad: "62", observaciones: "HTA, DLP, IAM/ACV, Parálisis Cerebral" },
  { nombre: "Manuel Antonio Manque Painen", edad: "79", observaciones: "HTA, DLP, Artrosis de Rodilla y Cadera" },
  { nombre: "Margarita Flor Huenumil Leal", edad: "70", observaciones: "Esquizofrenia, DLP, HTA, DM" },
  { nombre: "Maria Alicia Cea Cea", edad: "85", observaciones: "HTA, DLP, Alzheimer, Ant. IAM/ACV Isquémico 2010, Sd. Ocular Isquémico por estenosis carotídea (en estudio), DM2" },
  { nombre: "Maria Enriqueta Iribarra Frei", edad: "86", observaciones: "HTA, DM2, DLP, Cardiopatía Coronaria, Usuaria de TACO." },
  { nombre: "Maria Luzmila Trombert Perez", edad: "80", observaciones: "HTA, DLP, Esquizofrenia, Depresión" },
  { nombre: "Mario Ismael Morales Olivares", edad: "72", observaciones: "Cx de Cataratas, Epilepsia, Fx Cadera Derecha, HTA" },
  { nombre: "Maura Rebeca Hernandez Miranda", edad: "77", observaciones: "HTA, DLP, Artritis Reumatoide" },
  { nombre: "Misael Briones Contreras", edad: "86", observaciones: "Fx de cadera no operada, HTA, HPB, Ant de CA Colon Rectal" },
  { nombre: "Norma Eliana Dubreuil Gomez", edad: "84", observaciones: "HTA, Demencia Tipo Alzheimer" },
  { nombre: "Norma de las Mercedes Araneda Gutierrez", edad: "83", observaciones: "HTA, Demencia, Paraparesia, Trastorno Depresivo, DL, Artrosis" },
  { nombre: "Octavio del Carmen Escalona Ferrer", edad: "79", observaciones: "HTA" },
  { nombre: "Olivia del Carmen Aravena Rosales", edad: "81", observaciones: "HTA, DLP, AR Rodillas y Manos, Prótesis Total Cadera Izq. Demencia, Resistente a la Insulina" },
  { nombre: "Oscar Roberto Cordova Navarrete", edad: "78", observaciones: "HTA, DLP, Alcoholismo Crónico, Obesidad" },
  { nombre: "Patricio Marcelo Bustos Candia", edad: "53", observaciones: "Parálisis Cerebral, Anemia Moderada, Pie Equino Bilateral, Institucionalizado" },
  { nombre: "Pedro Contreras Contreras", edad: "91", observaciones: "HTA, DLP, IRC, Demencia, Cataratas, DBM2, Dermatitis" },
  { nombre: "Rebeca Isabel Castillo Rodriguez", edad: "66", observaciones: "Coreo-Atetosis, Paralisis Cerebral, Sindrome de Postración" },
  { nombre: "Rosa Erminda Gallardo Ramirez", edad: "84", observaciones: "HTA, DM2, DLP, Artrosis de rodilla, Demencia por cuerpos de Lewis, Prolapso Genital" },
  { nombre: "Ruth Arlines Zapata Roa", edad: "67", observaciones: "Esquizofrenia, DLP, Hipotiroidismo, DM, Trastorno Delirante" },
  { nombre: "Ruth Gabriela Catalan Turra", edad: "75", observaciones: "Paresia Hemicuerpo Izq, Luxación Hombro Izq, Fx de Cadera no Operada, Meningitis 2022, LPP Zona Sacra" },
  { nombre: "Sandro Daniel Nahuelpan Nahuelpan", edad: "53", observaciones: "Esquizofrenia, Epilepsia, Constipación Crónica" },
  { nombre: "Sergio Baldovino Riffo Carillanca", edad: "66", observaciones: "DHC por OH, Déficit Cognitivo, Hipoacusia" },
  { nombre: "Sonia España Paillaman", edad: "60", observaciones: "DLP, HTA, Hipotiroidismo, Esquizofrenia" },
  { nombre: "Telinda Alvarez Arias", edad: "94", observaciones: "HTA, DM2 IR, Artrosis, ERC, Demencia por Alzheimer" },
  { nombre: "Teofilo Ruderlindo Gomez Saez", edad: "80", observaciones: "Defecto de Coagulación, HTA, DLP, Hidrocefalia, OBS Enf. Pulmonar, Arritmia Cardiaca" },
  { nombre: "Violeta del Carmen Maeza Lavin", edad: "66", observaciones: "Esquizofrenia" },
  { nombre: "Viviana del Carmen Mathias Alcarraz", edad: "87", observaciones: "HTA, DLP, Hipotiroidismo, Demencia por Alzheimer" },
];
